require("uno.plugins")
require("uno.config")
require("uno.notify")
-- require("uno.lushTheming")
require("uno.lualine.evil")
require("uno.lsp")
require("uno.neoformat")
require("uno.comment")
require("uno.colorizer")
require("uno.dressing")
require("uno.fileTree")
require("uno.telescope")
require("uno.treesitter")
require("uno.zenmode")
require("uno.bufferline")
require("uno.highlights")
require("uno.icons")
require("uno.gitsigns")
require("uno.terminal")
require("uno.diffview")
require("uno.luasnip")
require("uno.keybindings")
require("uno.tree")
-- require("uno.sessions")
require("uno.workspaces")
require("uno.refactoring")
require("uno.navigator")

-- WHY DOESN"T THIS FUCKEN WORK
-- require("uno.quickfix")

-- require("uno.statusline")
-- require("uno.modes")
